In [2]:
import pandas as pd
import numpy as npp

from transformers import AutoTokenizer

import warnings
warnings.filterwarnings('ignore')

In [3]:
checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

### Tokenization :

Tokenization is the process of breaking down a sequence of text into smaller units, called tokens. Tokens are the building blocks of natural language processing (NLP) tasks, and they can represent words, subwords, characters, or other meaningful units depending on the context and the chosen tokenizer. Tokenization is a crucial step in processing and analyzing text data in various NLP applications.

In [4]:
tokenizer('hello world')

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [5]:
tokens = tokenizer.tokenize('hello world')

In [6]:
tokens

['hello', 'world']

In [7]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[7592, 2088]

In [8]:
tokenizer.decode(ids)

'hello world'

In [9]:
ids = tokenizer.encode('hello world')
ids

[101, 7592, 2088, 102]

In [11]:
 tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [12]:
model_inputs = tokenizer('hello world')
model_inputs

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [16]:
data = [
    'I like Animes.', 
    'Do you like Animes too?',
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8750, 2015, 1012, 102], [101, 2079, 2017, 2066, 8750, 2015, 2205, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1]]}

### Models in NLP :

NLP models, ranging from rule-based to advanced deep learning architectures like BERT and GPT, aim to understand and process human language. Statistical models and machine learning classifiers, such as SVM and Naive Bayes, were early contributors. Recent breakthroughs like Transformers have dominated NLP tasks, utilizing attention mechanisms for improved performance. Pre-trained models like BERT and GPT offer transfer learning capabilities, while multimodal models integrate language understanding with vision or audio processing for diverse applications. 

AutoModelForSequenceClassification is a class that automatically loads a pre-trained model for sequence classification tasks. Sequence classification involves assigning a label to an input sequence, such as classifying a document into different categories or determining the sentiment of a text.

In [17]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
model_inputs = tokenizer('hello world', return_tensors = 'pt')
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [20]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.1938,  0.1870]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [21]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels = 3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [22]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.5537,  0.1507, -0.0046]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [24]:
outputs.logits

tensor([[-0.5537,  0.1507, -0.0046]], grad_fn=<AddmmBackward0>)

In [26]:
data = [
    'I like Animes.', 
    'Do you like Animes too?',
]
model_inputs = tokenizer(data,padding = True, truncation = True, return_tensors = 'pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8750, 2015, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8750, 2015, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [27]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8750, 2015, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8750, 2015, 2205, 1029,  102]])

In [28]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.6513,  0.1576, -0.0147],
        [-0.6179,  0.1732, -0.0269]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)